### ISSUE TITLE
chore: add `openedx.yaml` file

### ISSUE THREAD

**Issue by OmarIthawi** [openedx/openedx-translations#3153]
### Description

@brian-smith-tcril Do you think this repository needs the `openedx.yaml` file?

**Comment by brian-smith-tcril** [comment]
`openedx.yaml` is being [deprecated](https://github.com/openedx/axim-engineering/issues/882)

the plan going forward is to [use `catalog-info.yaml` for release info](https://github.com/openedx/repo-tools/issues/439)

**Comment by OmarIthawi** [comment]
Thanks for noting that Brian. I'm closing this one.
