### ISSUE TITLE
[TX Request] Fix Hindi translation string

### ISSUE THREAD

**Issue by rgraber** [openedx/openedx-translations#75]
### Description

Translation job failed with 
`Execution of msgfmt failed: /edx/var/jenkins/jobs/translations/jobs/edx-platform-pull_translations/workspace/ecommerce-scripts/edx-platform/conf/locale/hi/LC_MESSAGES/django-partial.po:2541: 'msgstr[0]' is not a valid Python brace format string, unlike 'msgid_plural'. Reason: In the directive number 0, '�' cannot start a field name.
20:36:07 msgfmt: found 1 fatal error`
I'm having trouble finding the actual string that caused this because I don't have Transifex access.

**Comment by timmc-edx** [comment]
I'm not sure exactly which one this is failing on, but I noticed that a number of the django-partial Hindi translations on Transifex have the format-string `{identifiers}` translated. That's probably the nature of the problem. I have Transifex access but I can't figure out how to get it to show me just the ones with warnings. (`check:warning` doesn't seem like it's giving a relevant result.)

**Comment by timmc-edx** [comment]
I found the one that provoked this by downloading the .po file from Transifex and going to the line number, but I'm waiting to take action pending this discussion in `#wg-translations`: https://openedx.slack.com/archives/C037XDB9KN1/p1673981319936169

**Comment by timmc-edx** [comment]
Fixed, mostly thanks to the help of @pkulkark!
